// Host side for triattn_m1_sm90.cuh: TMA descriptor construction and launch of one Traits instantiation. Included by the per-flags
// translation units generated by triattn_m1.py.
#pragma once
#include <torch/types.h>
#include <ATen/cuda/CUDAContext.h>
#include <c10/cuda/CUDAGuard.h>

#include <cutlass/cluster_launch.hpp>

#include "triattn_m1_sm90.cuh"

namespace triattn_m1 {

struct Args {
    torch::Tensor const& q; torch::Tensor const& k; torch::Tensor const& v;
    torch::Tensor const& bias;                                   // staged [B*H, nq, 4*nk, 4096] fp32 (stage_bias_m1)
    double scale;
    torch::Tensor& out;
    int* fix;                                                    // [1 + 3 * n_ctas] int32: fix-list counter + (qtile, rowgroup, bh) triples (counter zeroed by stage_bias)
    int* fix_total;                                              // int32[2] device census accumulator
    uint32_t const* maskw; uint8_t const* rowkind; int const* kcend; int const* kcstart;   // key-mask staging (null: no mask)
    int const* rowkc0; int const* rowkc1;                        // per-row first / one-past-last attended 32-key column
    unsigned long long* trace = nullptr;
    int force_fix = 0;                                           // debug (env TRIATTN_M1_FORCE_SAFE=1): every tile through the SAFE pass
};

using RunFn = void (*)(Args const&);

template <class T>
void launch_m1(Args const& a) {
    using namespace cute;
    using Element = typename T::Element;
    int const B = a.q.size(0), N = a.q.size(1), H = a.q.size(2), S = a.q.size(3), D = a.q.size(4);
    TORCH_CHECK(D == T::kHeadDim, "head dim must be 32");
    typename T::ShapeQK shape_qk = make_shape(S, D, H, N, B);
    auto stride_of = [](torch::Tensor const& t) { return typename T::StrideQK{t.stride(3), _1{}, t.stride(2), t.stride(1), t.stride(0)}; };
    Tensor mQ = make_tensor(make_gmem_ptr(reinterpret_cast<Element const*>(a.q.data_ptr())), shape_qk, stride_of(a.q));
    Tensor mK = make_tensor(make_gmem_ptr(reinterpret_cast<Element const*>(a.k.data_ptr())), shape_qk, stride_of(a.k));
    Tensor mV = make_tensor(make_gmem_ptr(reinterpret_cast<Element const*>(a.v.data_ptr())), shape_qk, stride_of(a.v));
    int const n_qtiles = (S + T::kBlockM - 1) / T::kBlockM;
    int const n_ktiles = (S + T::kBlockN - 1) / T::kBlockN;
    TORCH_CHECK(a.bias.dim() == 4 && a.bias.size(0) == B * H && a.bias.size(1) == n_qtiles && a.bias.size(2) == 4 * (n_ktiles + 1) && a.bias.size(3) == T::kSlotElems
                && a.bias.is_contiguous() && a.bias.scalar_type() == torch::kFloat32, "staged bias has the wrong shape (stage_bias_m1)");
    int const n_kcol = 4 * (n_ktiles + 1);                      // 32-key columns staged per q-tile: one extra tile of -inf columns so a column-shifted tile stream stays in range
    typename T::ShapeB shape_b = make_shape(256, 8, 2 * n_kcol, n_qtiles, B * H);             // half-slot blocks of 2048 fp32: index 2*kc + h
    typename T::StrideB stride_b{_1{}, _256{}, int64_t(T::kHalfElems), int64_t(T::kSlotElems) * n_kcol, int64_t(T::kSlotElems) * n_kcol * n_qtiles};
    Tensor mB = make_tensor(make_gmem_ptr(a.bias.data_ptr<float>()), shape_b, stride_b);

    typename T::TMA_Q tma_q = make_tma_copy(SM90_TMA_LOAD{}, mQ, take<0, 2>(typename T::SmemLayoutQ{}), make_shape(Int<T::kBlockM>{}, Int<T::kHeadDim>{}), _1{});
    typename T::TMA_K tma_k = make_tma_copy(SM90_TMA_LOAD{}, mK, take<0, 2>(typename T::SmemLayoutK{}), make_shape(Int<T::kBlockN>{}, Int<T::kHeadDim>{}), _1{});
    typename T::TMA_V tma_v = make_tma_copy(SM90_TMA_LOAD{}, mV, take<0, 2>(typename T::SmemLayoutV{}), make_shape(Int<T::kBlockN>{}, Int<T::kHeadDim>{}), _1{});
    typename T::TMA_B tma_b = make_tma_copy(typename T::GmemTiledCopyB{}, mB, typename T::SmemLayoutBiasHalf{}, make_shape(_256{}, _8{}), Int<T::CR>{});
    typename T::TMA_BT tma_bt = make_tma_copy(SM90_TMA_LOAD{}, mB, typename T::SmemLayoutBiasThin{}, make_shape(_256{}, _1{}), _1{});

    typename T::Params p{tma_q, tma_k, tma_v, tma_b, tma_bt, shape_qk, shape_b,
        reinterpret_cast<Element*>(a.out.data_ptr()), a.out.stride(0), a.out.stride(1), a.out.stride(2), a.out.stride(3),
        S, N, H, n_qtiles, n_ktiles, float(a.scale), a.trace, int(a.q.size(3) >> 40), a.fix, a.fix_total, a.force_fix, a.maskw, a.rowkind, a.kcend, a.kcstart, n_kcol, a.rowkc0, a.rowkc1};   // zero: 0 for any real tensor, opaque to the compiler

    int smem = sizeof(typename T::SharedStorage);
    static bool configured = false;   // per instantiation
    if (!configured) {
        C10_CUDA_CHECK(cudaFuncSetAttribute((void const*)triattn_m1_kernel<T>, cudaFuncAttributeMaxDynamicSharedMemorySize, smem));
        configured = true;
    }
    int n_rg = (N + T::R - 1) / T::R;
    n_rg = (n_rg + T::CR - 1) / T::CR * T::CR;                  // cluster padding: extra CTAs run on clamped rows and store nothing
    dim3 grid(n_qtiles, n_rg, B * H), block(T::kNumThreads);
    int64_t const n_ctas = int64_t(n_qtiles) * n_rg * B * H;
    if constexpr (T::kSafe) { grid = dim3(unsigned(std::min<int64_t>(n_ctas, 66)), 1, 1); }    // persistent over the fix list (empty or tiny in practice: few CTAs = cheap empty launch)
    cudaStream_t stream = at::cuda::getCurrentCUDAStream();
    if constexpr (T::CR > 1 && !T::kList) {
        dim3 cluster(1, T::CR, 1);
        cutlass::ClusterLaunchParams lp{grid, block, cluster, smem, stream};
        cutlass::Status st = cutlass::launch_kernel_on_cluster(lp, (void const*)triattn_m1_kernel<T>, p);
        TORCH_CHECK(st == cutlass::Status::kSuccess, "cluster launch failed");
    } else {
        triattn_m1_kernel<T><<<grid, block, smem, stream>>>(p);
    }
    C10_CUDA_KERNEL_LAUNCH_CHECK();
}

template <class T>
int64_t smem_bytes_m1() { return sizeof(typename T::SharedStorage); }

}  // namespace triattn_m1
